package com._3145275._3145275;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Full Name")
	private java.lang.String fullname;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Date Birth")
	private java.time.LocalDateTime dateBirth;
	public Person() {
	}

	public java.lang.String getFullname() {
		return this.fullname;
	}

	public void setFullname(java.lang.String fullname) {
		this.fullname = fullname;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.time.LocalDateTime getDateBirth() {
		return this.dateBirth;
	}

	public void setDateBirth(java.time.LocalDateTime dateBirth) {
		this.dateBirth = dateBirth;
	}

	public Person(java.lang.String fullname, java.lang.Integer age,
			java.time.LocalDateTime dateBirth) {
		this.fullname = fullname;
		this.age = age;
		this.dateBirth = dateBirth;
	}

}